# Generated by Django 4.0 on 2022-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userfollowers_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_followers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_following',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
