# Generated by Django 4.0 on 2022-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_pic_profile_total_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profiles/default.png', null=True, upload_to='profiles'),
        ),
    ]
