# Generated by Django 4.0 on 2022-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
